# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:lints/core.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
#    constant_identifier_names: false
#    non_constant_identifier_names: false
#    prefer_void_to_null: false
#    avoid_function_literals_in_foreach_calls: false
#    void_checks: false

analyzer:
  exclude: [build/**]
