name: alfred
description: A performant, expressjs like server framework thats easy to use and has all the bits in one place.
version: 0.1.5
repository: https://github.com/rknell/alfred

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mime: ^1.0.0
  mime_type: ^1.0.0
  enum_to_string: ^2.0.1
  queue: ^3.1.0
  angel3_range_header: ^3.0.1

dev_dependencies:
  test: ^1.14.4
  web_socket_channel: ^2.0.0
  logging: ^1.0.1
  http: ^0.13.2
  pedantic: ^1.11.0
